name: Build and Release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build project
      run: npm install && npm ci && npm run build

    - name: Get Previous tag
      id: previoustag
      uses: WyriHaximus/github-action-get-previous-tag@v1
      with:
        fallback: 0.0.4

    - name: Create Release
      uses: ncipollo/release-action@v1.12.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        TAG_NAME: ${{ steps.previoustag.outputs.tag }}
      with:
        tag: ${{ env.TAG_NAME }}
        name: Release ${{ env.TAG_NAME }}
        draft: false
        prerelease: false
        generateReleaseNotes: true
        makeLatest: true
        artifacts: "main.js,manifest.json,styles.css"
